### ISSUE TITLE
claim reward in tron

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/wallet-cli#427]
Hi,
I am trying to claim reward in tron-wallet-cli.
**Command:** withdrawbalance [owner_address].
But it results Account[hex_address] is a guard representative and is not allowed to withdraw balance.

What am i doing wrong?

**Comment by Psykik-byte** [comment]
im having same problems

**Comment by vivian-kang** [comment]
The configure items in genesis.block section in main_net_config.conf are the genesis block info. And the witnesses in this section are called guard representatives, they are used to generate genesis block, they are not allowed to withdraw balance.
so for mainnet, you should not modify the genesis.block section, otherwise your node will not connect to mainnet successfully. for test net, if you withdraw reward for account address in genesis.block.witnesses, this exception will be shown.

**Comment by Benson0224** [comment]
Thanks for your contribution to wallet-cli, this issue will be closed since no update for a long time.
Please feel free to re-open it if you still see the issue in the latest version. thanks.
