### ISSUE TITLE
question with ref_block_bytes and block_hash?

### ISSUE THREAD

**Issue by janjanEnjoy** [tronprotocol/wallet-cli#431]
![image](https://user-images.githubusercontent.com/31478775/115665206-869efe80-a375-11eb-9368-098e71e6c9eb.png)
How is the blockNum 3 bytes for 8 using? like "13802595".
And then,  if i broad this transaction ,is this the blockHeight "13802595" shall be the block with this transaction on?
ask for your help, thank you!!

**Comment by joe192** [comment]
13802595 should be blockheight

**Comment by vivian-kang** [comment]
hello @janjanEnjoy ,
RefBlockBytes and RefBlockHash are used for fast validation transaction for reference block, check if the ref block is at the same chain with the transaction.  these two value stored in RecentBlockStore, and no need to store the whole blocknum, because for the blocks which have the same RefBlockBytes value, they are generated very long ago, and it's meaningless to ref to them.

**Comment by zyumingfit** [comment]
@janjanEnjoy Not what you understand, every legal transaction needs to have a block that has existed on the chain for a certain period of time as a reference block. If the block used as a reference block when you create a transaction is rolled back or is not new enough, the transaction cannot be packaged

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time. 

Thanks for your contribution to wallet-cli. Please feel free to re-open it if you still have any questions. thanks.
